<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 9 Week 6: Correlations | MSc Conversion in Psychological Studies ODL</title>
  <meta name="description" content="This is the materials for the one-year MSc Conversion in Psychological Studies ODL programme." />
  <meta name="generator" content="bookdown 0.11 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 9 Week 6: Correlations | MSc Conversion in Psychological Studies ODL" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is the materials for the one-year MSc Conversion in Psychological Studies ODL programme." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 9 Week 6: Correlations | MSc Conversion in Psychological Studies ODL" />
  
  <meta name="twitter:description" content="This is the materials for the one-year MSc Conversion in Psychological Studies ODL programme." />
  



<meta name="date" content="2019-07-28" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="week-5-r-markdown.html">

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="include\psyteachr.css" type="text/css" />
<link rel="stylesheet" href="include\style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">MSc Conversion in Psychological Studies/Science (face-to-face)</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Overview</a><ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#how-to-use-this-book"><i class="fa fa-check"></i><b>0.1</b> How to use this book</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#intended-learning-outcomes"><i class="fa fa-check"></i><b>0.2</b> Intended Learning Outcomes</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="ref3.html"><a href="ref3.html"><i class="fa fa-check"></i><b>1</b> Programming Basics</a><ul>
<li class="chapter" data-level="1.1" data-path="ref3.html"><a href="ref3.html#notes-for-instructors"><i class="fa fa-check"></i><b>1.1</b> Notes for instructors</a></li>
<li class="chapter" data-level="1.2" data-path="ref3.html"><a href="ref3.html#introduction"><i class="fa fa-check"></i><b>1.2</b> Introduction</a></li>
<li class="chapter" data-level="1.3" data-path="ref3.html"><a href="ref3.html#r-and-r-studio"><i class="fa fa-check"></i><b>1.3</b> R and R Studio</a><ul>
<li class="chapter" data-level="1.3.1" data-path="ref3.html"><a href="ref3.html#getting-to-know-r-studio"><i class="fa fa-check"></i><b>1.3.1</b> Getting to know R Studio</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="ref3.html"><a href="ref3.html#functions-and-arguments"><i class="fa fa-check"></i><b>1.4</b> Functions and arguments</a><ul>
<li class="chapter" data-level="1.4.1" data-path="ref3.html"><a href="ref3.html#argument-names"><i class="fa fa-check"></i><b>1.4.1</b> Argument names</a></li>
<li class="chapter" data-level="1.4.2" data-path="ref3.html"><a href="ref3.html#tab-auto-complete"><i class="fa fa-check"></i><b>1.4.2</b> Tab auto-complete</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="ref3.html"><a href="ref3.html#packages"><i class="fa fa-check"></i><b>1.5</b> Base R and packages</a><ul>
<li class="chapter" data-level="1.5.1" data-path="ref3.html"><a href="ref3.html#installing-and-loading-packages"><i class="fa fa-check"></i><b>1.5.1</b> Installing and loading packages</a></li>
<li class="chapter" data-level="1.5.2" data-path="ref3.html"><a href="ref3.html#package-updates"><i class="fa fa-check"></i><b>1.5.2</b> Package updates</a></li>
<li class="chapter" data-level="1.5.3" data-path="ref3.html"><a href="ref3.html#conflicts"><i class="fa fa-check"></i><b>1.5.3</b> Package conflicts</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="ref3.html"><a href="ref3.html#objects"><i class="fa fa-check"></i><b>1.6</b> Objects</a></li>
<li class="chapter" data-level="1.7" data-path="ref3.html"><a href="ref3.html#looking-after-the-environment"><i class="fa fa-check"></i><b>1.7</b> Looking after the environment</a></li>
<li class="chapter" data-level="1.8" data-path="ref3.html"><a href="ref3.html#r-sessions"><i class="fa fa-check"></i><b>1.8</b> R sessions</a></li>
<li class="chapter" data-level="1.9" data-path="ref3.html"><a href="ref3.html#help-and-additional-resources"><i class="fa fa-check"></i><b>1.9</b> Help and additional resources</a></li>
<li class="chapter" data-level="1.10" data-path="ref3.html"><a href="ref3.html#debugging-tips"><i class="fa fa-check"></i><b>1.10</b> Debugging tips</a></li>
<li class="chapter" data-level="1.11" data-path="ref3.html"><a href="ref3.html#test-yourself"><i class="fa fa-check"></i><b>1.11</b> Test yourself</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="ref2.html"><a href="ref2.html"><i class="fa fa-check"></i><b>2</b> Revision 1: Intro to R</a><ul>
<li class="chapter" data-level="2.0.1" data-path="ref2.html"><a href="ref2.html#activity-1-programming-basics"><i class="fa fa-check"></i><b>2.0.1</b> Activity 1: Programming basics</a></li>
<li class="chapter" data-level="2.0.2" data-path="ref2.html"><a href="ref2.html#activity-2-create-the-working-directory"><i class="fa fa-check"></i><b>2.0.2</b> Activity 2: Create the working directory</a></li>
<li class="chapter" data-level="2.0.3" data-path="ref2.html"><a href="ref2.html#activity-3-set-the-working-directory"><i class="fa fa-check"></i><b>2.0.3</b> Activity 3: Set the working directory</a></li>
<li class="chapter" data-level="2.0.4" data-path="ref2.html"><a href="ref2.html#r-markdown-for-r-book-work-and-portfolio-assignments"><i class="fa fa-check"></i><b>2.0.4</b> R Markdown for R book work and portfolio assignments</a></li>
<li class="chapter" data-level="2.0.5" data-path="ref2.html"><a href="ref2.html#activity-4-open-and-save-a-new-r-markdown-document"><i class="fa fa-check"></i><b>2.0.5</b> Activity 4: Open and save a new R Markdown document</a></li>
<li class="chapter" data-level="2.0.6" data-path="ref2.html"><a href="ref2.html#activity-5-create-a-new-code-chunk"><i class="fa fa-check"></i><b>2.0.6</b> Activity 5: Create a new code chunk</a></li>
<li class="chapter" data-level="2.0.7" data-path="ref2.html"><a href="ref2.html#activity-6-write-some-code"><i class="fa fa-check"></i><b>2.0.7</b> Activity 6: Write some code</a></li>
<li class="chapter" data-level="2.0.8" data-path="ref2.html"><a href="ref2.html#running-code"><i class="fa fa-check"></i><b>2.0.8</b> Running code</a></li>
<li class="chapter" data-level="2.0.9" data-path="ref2.html"><a href="ref2.html#activity-7-run-your-code"><i class="fa fa-check"></i><b>2.0.9</b> Activity 7: Run your code</a></li>
<li class="chapter" data-level="2.0.10" data-path="ref2.html"><a href="ref2.html#activity-8-inline-code"><i class="fa fa-check"></i><b>2.0.10</b> Activity 8: Inline code</a></li>
<li class="chapter" data-level="2.0.11" data-path="ref2.html"><a href="ref2.html#activity-9-knitting-your-file"><i class="fa fa-check"></i><b>2.0.11</b> Activity 9: Knitting your file</a></li>
<li class="chapter" data-level="2.0.12" data-path="ref2.html"><a href="ref2.html#finished"><i class="fa fa-check"></i><b>2.0.12</b> Finished</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="lab1-inclass.html"><a href="lab1-inclass.html"><i class="fa fa-check"></i><b>3</b> Revision 2</a><ul>
<li class="chapter" data-level="3.0.1" data-path="lab1-inclass.html"><a href="lab1-inclass.html#getting-data-ready-to-work-with"><i class="fa fa-check"></i><b>3.0.1</b> Getting data ready to work with</a></li>
<li class="chapter" data-level="3.0.2" data-path="lab1-inclass.html"><a href="lab1-inclass.html#activity-1-set-up"><i class="fa fa-check"></i><b>3.0.2</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="3.0.3" data-path="lab1-inclass.html"><a href="lab1-inclass.html#activity-2-load-in-the-package"><i class="fa fa-check"></i><b>3.0.3</b> Activity 2: Load in the package</a></li>
<li class="chapter" data-level="3.0.4" data-path="lab1-inclass.html"><a href="lab1-inclass.html#open-data"><i class="fa fa-check"></i><b>3.0.4</b> Open data</a></li>
<li class="chapter" data-level="3.0.5" data-path="lab1-inclass.html"><a href="lab1-inclass.html#activity-3-read-in-data"><i class="fa fa-check"></i><b>3.0.5</b> Activity 3: Read in data</a></li>
<li class="chapter" data-level="3.0.6" data-path="lab1-inclass.html"><a href="lab1-inclass.html#activity-4-check-yo-data"><i class="fa fa-check"></i><b>3.0.6</b> Activity 4: Check yo’ data</a></li>
<li class="chapter" data-level="3.0.7" data-path="lab1-inclass.html"><a href="lab1-inclass.html#activity-5-join-the-files-together"><i class="fa fa-check"></i><b>3.0.7</b> Activity 5: Join the files together</a></li>
<li class="chapter" data-level="3.0.8" data-path="lab1-inclass.html"><a href="lab1-inclass.html#ref1"><i class="fa fa-check"></i><b>3.0.8</b> Activity 6: Pull out variables of interest</a></li>
<li class="chapter" data-level="3.1" data-path="lab1-inclass.html"><a href="lab1-inclass.html#debugging-tips-1"><i class="fa fa-check"></i><b>3.1</b> Debugging tips</a></li>
<li class="chapter" data-level="3.2" data-path="lab1-inclass.html"><a href="lab1-inclass.html#test-yourself-1"><i class="fa fa-check"></i><b>3.2</b> Test yourself</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="week-1-data-wrangling-1.html"><a href="week-1-data-wrangling-1.html"><i class="fa fa-check"></i><b>4</b> Week 1: Data wrangling 1</a><ul>
<li class="chapter" data-level="4.0.1" data-path="week-1-data-wrangling-1.html"><a href="week-1-data-wrangling-1.html#the-babynames-database"><i class="fa fa-check"></i><b>4.0.1</b> The <code>babynames</code> database</a></li>
<li class="chapter" data-level="4.0.2" data-path="week-1-data-wrangling-1.html"><a href="week-1-data-wrangling-1.html#activity-1-set-up-1"><i class="fa fa-check"></i><b>4.0.2</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="4.0.3" data-path="week-1-data-wrangling-1.html"><a href="week-1-data-wrangling-1.html#activity-2-look-at-the-data"><i class="fa fa-check"></i><b>4.0.3</b> Activity 2: Look at the data</a></li>
<li class="chapter" data-level="4.0.4" data-path="week-1-data-wrangling-1.html"><a href="week-1-data-wrangling-1.html#activity-3-your-first-plot"><i class="fa fa-check"></i><b>4.0.4</b> Activity 3: Your first plot</a></li>
<li class="chapter" data-level="4.0.5" data-path="week-1-data-wrangling-1.html"><a href="week-1-data-wrangling-1.html#activity-4-selecting-variables-of-interest"><i class="fa fa-check"></i><b>4.0.5</b> Activity 4: Selecting variables of interest</a></li>
<li class="chapter" data-level="4.0.6" data-path="week-1-data-wrangling-1.html"><a href="week-1-data-wrangling-1.html#activity-5-arranging-the-data"><i class="fa fa-check"></i><b>4.0.6</b> Activity 5: Arranging the data</a></li>
<li class="chapter" data-level="4.0.7" data-path="week-1-data-wrangling-1.html"><a href="week-1-data-wrangling-1.html#activity-6-using-filter-to-select-observations"><i class="fa fa-check"></i><b>4.0.7</b> Activity 6: Using filter to select observations</a></li>
<li class="chapter" data-level="4.0.8" data-path="week-1-data-wrangling-1.html"><a href="week-1-data-wrangling-1.html#activity-7-creating-new-variables"><i class="fa fa-check"></i><b>4.0.8</b> Activity 7: Creating new variables</a></li>
<li class="chapter" data-level="4.0.9" data-path="week-1-data-wrangling-1.html"><a href="week-1-data-wrangling-1.html#activity-8-grouping-and-summarising"><i class="fa fa-check"></i><b>4.0.9</b> Activity 8: Grouping and summarising</a></li>
<li class="chapter" data-level="4.0.10" data-path="week-1-data-wrangling-1.html"><a href="week-1-data-wrangling-1.html#activity-9-pipes"><i class="fa fa-check"></i><b>4.0.10</b> Activity 9: Pipes</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="week-2-data-wrangling-2.html"><a href="week-2-data-wrangling-2.html"><i class="fa fa-check"></i><b>5</b> Week 2: Data wrangling 2</a><ul>
<li class="chapter" data-level="5.0.1" data-path="week-2-data-wrangling-2.html"><a href="week-2-data-wrangling-2.html#learning-to-wrangle-is-there-a-chastity-belt-on-perception"><i class="fa fa-check"></i><b>5.0.1</b> Learning to wrangle: Is there a chastity belt on perception</a></li>
<li class="chapter" data-level="5.0.2" data-path="week-2-data-wrangling-2.html"><a href="week-2-data-wrangling-2.html#activity-1-set-up-2"><i class="fa fa-check"></i><b>5.0.2</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="5.0.3" data-path="week-2-data-wrangling-2.html"><a href="week-2-data-wrangling-2.html#activity-2-look-at-your-data"><i class="fa fa-check"></i><b>5.0.3</b> Activity 2: Look at your data</a></li>
<li class="chapter" data-level="5.0.4" data-path="week-2-data-wrangling-2.html"><a href="week-2-data-wrangling-2.html#activity-3-select"><i class="fa fa-check"></i><b>5.0.4</b> Activity 3: <strong><code>select()</code></strong></a></li>
<li class="chapter" data-level="5.0.5" data-path="week-2-data-wrangling-2.html"><a href="week-2-data-wrangling-2.html#activity-4-reorder-the-variables"><i class="fa fa-check"></i><b>5.0.5</b> Activity 4: Reorder the variables</a></li>
<li class="chapter" data-level="5.0.6" data-path="week-2-data-wrangling-2.html"><a href="week-2-data-wrangling-2.html#activity-5-arrange-f"><i class="fa fa-check"></i><b>5.0.6</b> Activity 5: <strong><code>arrange()</code></strong> F</a></li>
<li class="chapter" data-level="5.0.7" data-path="week-2-data-wrangling-2.html"><a href="week-2-data-wrangling-2.html#activity-6-filter"><i class="fa fa-check"></i><b>5.0.7</b> Activity 6: <code>filter()</code></a></li>
<li class="chapter" data-level="5.0.8" data-path="week-2-data-wrangling-2.html"><a href="week-2-data-wrangling-2.html#activity-7-mutate"><i class="fa fa-check"></i><b>5.0.8</b> Activity 7: <code>mutate()</code></a></li>
<li class="chapter" data-level="5.0.9" data-path="week-2-data-wrangling-2.html"><a href="week-2-data-wrangling-2.html#activity-8-group_by"><i class="fa fa-check"></i><b>5.0.9</b> Activity 8: <code>group_by()</code></a></li>
<li class="chapter" data-level="5.0.10" data-path="week-2-data-wrangling-2.html"><a href="week-2-data-wrangling-2.html#activity-9-summarising-data"><i class="fa fa-check"></i><b>5.0.10</b> Activity 9: Summarising data</a></li>
<li class="chapter" data-level="5.0.11" data-path="week-2-data-wrangling-2.html"><a href="week-2-data-wrangling-2.html#two-other-useful-functions"><i class="fa fa-check"></i><b>5.0.11</b> Two other useful functions</a></li>
<li class="chapter" data-level="5.0.12" data-path="week-2-data-wrangling-2.html"><a href="week-2-data-wrangling-2.html#pipes"><i class="fa fa-check"></i><b>5.0.12</b> Pipes (<strong><code>%&gt;%</code></strong>)</a></li>
<li class="chapter" data-level="5.0.13" data-path="week-2-data-wrangling-2.html"><a href="week-2-data-wrangling-2.html#activity-solutions"><i class="fa fa-check"></i><b>5.0.13</b> Activity solutions</a></li>
<li class="chapter" data-level="5.1" data-path="week-2-data-wrangling-2.html"><a href="week-2-data-wrangling-2.html#debugging-tips-2"><i class="fa fa-check"></i><b>5.1</b> Debugging tips</a></li>
<li class="chapter" data-level="5.2" data-path="week-2-data-wrangling-2.html"><a href="week-2-data-wrangling-2.html#test-yourself-2"><i class="fa fa-check"></i><b>5.2</b> Test yourself</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="week-3-data-wrangling-3.html"><a href="week-3-data-wrangling-3.html"><i class="fa fa-check"></i><b>6</b> Week 3: Data Wrangling 3</a><ul>
<li class="chapter" data-level="6.0.1" data-path="week-3-data-wrangling-3.html"><a href="week-3-data-wrangling-3.html#tidy-data"><i class="fa fa-check"></i><b>6.0.1</b> Tidy data</a></li>
<li class="chapter" data-level="6.0.2" data-path="week-3-data-wrangling-3.html"><a href="week-3-data-wrangling-3.html#analysing-the-autism-spectrum-quotient-aq"><i class="fa fa-check"></i><b>6.0.2</b> Analysing the Autism Spectrum Quotient (AQ)</a></li>
<li class="chapter" data-level="6.0.3" data-path="week-3-data-wrangling-3.html"><a href="week-3-data-wrangling-3.html#activity-1-set-up-3"><i class="fa fa-check"></i><b>6.0.3</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="6.0.4" data-path="week-3-data-wrangling-3.html"><a href="week-3-data-wrangling-3.html#activity-2-load-in-the-data"><i class="fa fa-check"></i><b>6.0.4</b> Activity 2: Load in the data</a></li>
<li class="chapter" data-level="6.0.5" data-path="week-3-data-wrangling-3.html"><a href="week-3-data-wrangling-3.html#activity-3-look-at-your-data"><i class="fa fa-check"></i><b>6.0.5</b> Activity 3: Look at your data</a></li>
<li class="chapter" data-level="6.0.6" data-path="week-3-data-wrangling-3.html"><a href="week-3-data-wrangling-3.html#gather"><i class="fa fa-check"></i><b>6.0.6</b> Activity 4: Gathering data</a></li>
<li class="chapter" data-level="6.0.7" data-path="week-3-data-wrangling-3.html"><a href="week-3-data-wrangling-3.html#join"><i class="fa fa-check"></i><b>6.0.7</b> Activity 5: Combining data</a></li>
<li class="chapter" data-level="6.0.8" data-path="week-3-data-wrangling-3.html"><a href="week-3-data-wrangling-3.html#activity-6-combining-more-data"><i class="fa fa-check"></i><b>6.0.8</b> Activity 6: Combining more data</a></li>
<li class="chapter" data-level="6.0.9" data-path="week-3-data-wrangling-3.html"><a href="week-3-data-wrangling-3.html#activity-7-calculating-the-aq-scores."><i class="fa fa-check"></i><b>6.0.9</b> Activity 7: Calculating the AQ scores.</a></li>
<li class="chapter" data-level="6.0.10" data-path="week-3-data-wrangling-3.html"><a href="week-3-data-wrangling-3.html#activity-8-one-last-thing-on-pipes"><i class="fa fa-check"></i><b>6.0.10</b> Activity 8: One last thing on pipes</a></li>
<li class="chapter" data-level="6.0.11" data-path="week-3-data-wrangling-3.html"><a href="week-3-data-wrangling-3.html#activity-solutions-1"><i class="fa fa-check"></i><b>6.0.11</b> Activity solutions</a></li>
<li class="chapter" data-level="6.0.12" data-path="week-3-data-wrangling-3.html"><a href="week-3-data-wrangling-3.html#test-yourself-3"><i class="fa fa-check"></i><b>6.0.12</b> Test yourself</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="week-4.html"><a href="week-4.html"><i class="fa fa-check"></i><b>7</b> Week 4:</a><ul>
<li class="chapter" data-level="7.0.1" data-path="week-4.html"><a href="week-4.html#reminders-through-association"><i class="fa fa-check"></i><b>7.0.1</b> Reminders through association</a></li>
<li class="chapter" data-level="7.0.2" data-path="week-4.html"><a href="week-4.html#activity-1-set-up-4"><i class="fa fa-check"></i><b>7.0.2</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="7.0.3" data-path="week-4.html"><a href="week-4.html#activity-2-look-at-the-data-1"><i class="fa fa-check"></i><b>7.0.3</b> Activity 2: Look at the data</a></li>
<li class="chapter" data-level="7.0.4" data-path="week-4.html"><a href="week-4.html#activity-3-wrangle-and-recode-the-data"><i class="fa fa-check"></i><b>7.0.4</b> Activity 3: Wrangle and recode the data</a></li>
<li class="chapter" data-level="7.0.5" data-path="week-4.html"><a href="week-4.html#activity-4-descriptive-statistics"><i class="fa fa-check"></i><b>7.0.5</b> Activity 4: Descriptive statistics</a></li>
<li class="chapter" data-level="7.0.6" data-path="week-4.html"><a href="week-4.html#ggplot2"><i class="fa fa-check"></i><b>7.0.6</b> <code>ggplot2()</code></a></li>
<li class="chapter" data-level="7.0.7" data-path="week-4.html"><a href="week-4.html#bar"><i class="fa fa-check"></i><b>7.0.7</b> Activity 5: Bar plot</a></li>
<li class="chapter" data-level="7.0.8" data-path="week-4.html"><a href="week-4.html#activity-6-make-the-plot-pretty"><i class="fa fa-check"></i><b>7.0.8</b> Activity 6: Make the plot pretty</a></li>
<li class="chapter" data-level="7.0.9" data-path="week-4.html"><a href="week-4.html#optional-activity-1-chi-square"><i class="fa fa-check"></i><b>7.0.9</b> Optional activity 1: Chi-square</a></li>
<li class="chapter" data-level="7.0.10" data-path="week-4.html"><a href="week-4.html#optional-activity-2-additional-analysis-information"><i class="fa fa-check"></i><b>7.0.10</b> Optional activity 2: Additional analysis information</a></li>
<li class="chapter" data-level="7.0.11" data-path="week-4.html"><a href="week-4.html#assumption-checks"><i class="fa fa-check"></i><b>7.0.11</b> Assumption checks</a></li>
<li class="chapter" data-level="7.0.12" data-path="week-4.html"><a href="week-4.html#optional-activity-3-check-the-expected-frequencies"><i class="fa fa-check"></i><b>7.0.12</b> Optional activity 3: Check the expected frequencies</a></li>
<li class="chapter" data-level="7.0.13" data-path="week-4.html"><a href="week-4.html#cramer"><i class="fa fa-check"></i><b>7.0.13</b> Optional activity 4: Effect size</a></li>
<li class="chapter" data-level="7.0.14" data-path="week-4.html"><a href="week-4.html#optional-activity-5-write-up"><i class="fa fa-check"></i><b>7.0.14</b> Optional activity 5: Write-up</a></li>
<li class="chapter" data-level="7.0.15" data-path="week-4.html"><a href="week-4.html#activity-solutions-2"><i class="fa fa-check"></i><b>7.0.15</b> Activity solutions</a></li>
<li class="chapter" data-level="7.0.16" data-path="week-4.html"><a href="week-4.html#test-yourself-4"><i class="fa fa-check"></i><b>7.0.16</b> Test yourself</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="week-5-r-markdown.html"><a href="week-5-r-markdown.html"><i class="fa fa-check"></i><b>8</b> Week 5: R Markdown</a><ul>
<li class="chapter" data-level="8.0.1" data-path="week-5-r-markdown.html"><a href="week-5-r-markdown.html#advantages-of-using-r-markdown"><i class="fa fa-check"></i><b>8.0.1</b> Advantages of using R Markdown</a></li>
<li class="chapter" data-level="8.0.2" data-path="week-5-r-markdown.html"><a href="week-5-r-markdown.html#activity-1-create-a-new-markdown-document"><i class="fa fa-check"></i><b>8.0.2</b> Activity 1: Create a new Markdown document</a></li>
<li class="chapter" data-level="8.0.3" data-path="week-5-r-markdown.html"><a href="week-5-r-markdown.html#activity-2-setting-up-the-new-markdown-document"><i class="fa fa-check"></i><b>8.0.3</b> Activity 2: Setting up the new Markdown document</a></li>
<li class="chapter" data-level="8.0.4" data-path="week-5-r-markdown.html"><a href="week-5-r-markdown.html#activity-3-new-code-chunks"><i class="fa fa-check"></i><b>8.0.4</b> Activity 3: New code chunks</a></li>
<li class="chapter" data-level="8.0.5" data-path="week-5-r-markdown.html"><a href="week-5-r-markdown.html#activity-4-knit-your-code"><i class="fa fa-check"></i><b>8.0.5</b> Activity 4: Knit your code</a></li>
<li class="chapter" data-level="8.0.6" data-path="week-5-r-markdown.html"><a href="week-5-r-markdown.html#activity-5-adding-rules-to-code-chunks"><i class="fa fa-check"></i><b>8.0.6</b> Activity 5: Adding rules to code chunks</a></li>
<li class="chapter" data-level="8.0.7" data-path="week-5-r-markdown.html"><a href="week-5-r-markdown.html#activity-8-formatting-the-r-markdown-file"><i class="fa fa-check"></i><b>8.0.7</b> Activity 8: Formatting the R Markdown File</a></li>
<li class="chapter" data-level="8.0.8" data-path="week-5-r-markdown.html"><a href="week-5-r-markdown.html#test-yourself-5"><i class="fa fa-check"></i><b>8.0.8</b> Test yourself</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="week-6-correlations.html"><a href="week-6-correlations.html"><i class="fa fa-check"></i><b>9</b> Week 6: Correlations</a><ul>
<li class="chapter" data-level="9.0.1" data-path="week-6-correlations.html"><a href="week-6-correlations.html#activity-1-set-up-5"><i class="fa fa-check"></i><b>9.0.1</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="9.0.2" data-path="week-6-correlations.html"><a href="week-6-correlations.html#activity-2-look-at-your-data-1"><i class="fa fa-check"></i><b>9.0.2</b> Activity 2: Look at your data</a></li>
<li class="chapter" data-level="9.0.3" data-path="week-6-correlations.html"><a href="week-6-correlations.html#activity-3-assumptions"><i class="fa fa-check"></i><b>9.0.3</b> Activity 3: Assumptions</a></li>
<li class="chapter" data-level="9.0.4" data-path="week-6-correlations.html"><a href="week-6-correlations.html#activity-4-descriptive-statistics-1"><i class="fa fa-check"></i><b>9.0.4</b> Activity 4: Descriptive statistics</a></li>
<li class="chapter" data-level="9.0.5" data-path="week-6-correlations.html"><a href="week-6-correlations.html#activity-5-correlation"><i class="fa fa-check"></i><b>9.0.5</b> Activity 5: Correlation</a></li>
<li class="chapter" data-level="9.0.6" data-path="week-6-correlations.html"><a href="week-6-correlations.html#activity-6-interpreting-the-correlation"><i class="fa fa-check"></i><b>9.0.6</b> Activity 6: Interpreting the correlation</a></li>
<li class="chapter" data-level="9.0.7" data-path="week-6-correlations.html"><a href="week-6-correlations.html#activity-7-write-up"><i class="fa fa-check"></i><b>9.0.7</b> Activity 7: Write-up</a></li>
<li class="chapter" data-level="9.0.8" data-path="week-6-correlations.html"><a href="week-6-correlations.html#activity-8-scatterplot-matrix"><i class="fa fa-check"></i><b>9.0.8</b> Activity 8: Scatterplot matrix</a></li>
<li class="chapter" data-level="9.0.9" data-path="week-6-correlations.html"><a href="week-6-correlations.html#activity-9-multiple-correlations"><i class="fa fa-check"></i><b>9.0.9</b> Activity 9: Multiple correlations</a></li>
<li class="chapter" data-level="9.0.10" data-path="week-6-correlations.html"><a href="week-6-correlations.html#activity-solutions-3"><i class="fa fa-check"></i><b>9.0.10</b> Activity solutions</a></li>
</ul></li>
<li class="appendix"><span><b>Appendices</b></span></li>
<li class="divider"></li>
<li><a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/" 
    target="blank"><img alt="Creative Commons License" 
    style="border-width:0" 
    src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><li>
<li><a href="https://psyteachr.github.io/" target="blank">PsyTeachR</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">MSc Conversion in Psychological Studies ODL</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="week-6-correlations" class="section level1">
<h1><span class="header-section-number">Chapter 9</span> Week 6: Correlations</h1>
<p>As <a href="https://drive.google.com/file/d/0B1fyuTuvj3YoaFdUR3FZaXNuNXc/view">Miller and Haden (2013)</a> state at the start of Chapter 11, correlations are <strong>used to detect and quantify relationships among numerical variables</strong>. In short, you measure two variables and the correlation analysis tells you whether or not they are related in some manner - positively or negatively; one increases as the other increases; one decreases as the other increases; etc..</p>
<p>To actually carry out a correlation is very simple and we will show you that today in a little while: you just need the <code>cor.test()</code> function. The harder part of correlations is really wrangling the data and interpreting what the results mean. You are going to run a few correlations today to give you good practice at running and interpreting the relationships between two variables.</p>
<p><strong>Note:</strong> When dealing with correlations you should always refer to relationships and not predictions. In a correlation, X does not predict Y, that is regression which we will look at later this semester. In a correlation, all we can say is whether X and Y are related. So try to get the correct terminology and please feel free to pull us up if we say the wrong thing in class. It is an easy slip of the tongue to make!</p>
<div id="activity-1-set-up-5" class="section level3">
<h3><span class="header-section-number">9.0.1</span> Activity 1: Set-up</h3>
<p>In this chapter we will use the examples in Miller and Haden (2013), Chapter 11, looking at the relationship between four variables: reading ability, intelligence (IQ), the number of minutes per week spent reading at home (Home); and the number of minutes per week spent watching TV at home (TV). You can see in this situation that it would be unethical to manipulate these variables so measuring them as they exist in the environment is most appropriate; hence the use of correlations.</p>
<p>Do the following. If you need help, consult Chapter <a href="ref3.html#ref3">1</a> and Chapter @(ref2).</p>
<ul>
<li>Open R Studio and set the working directory to your Week 6 folder. Ensure the environment is clear.<br />
</li>
<li>Open a new R Markdown document and save it in your working directory. Call the file “Week 6”.<br />
</li>
<li>Download <a href="MillerHadenData.csv" download>MillerHadenData.csv</a> and save it in your Week 6 folder. Make sure that you do not change the file name at all.<br />
</li>
<li>If you are working on your own computer, install the packages <code>Hmisc</code>, <code>car</code>, and <code>broom</code>. Remember <strong>do not install packages on university computers, they are already installed</strong>.</li>
<li>Delete the default R Markdown welcome text and insert a new code chunk that loads the packages <code>broom</code>, <code>car</code>, <code>lsr</code>, <code>Hmisc</code>, and <code>tidyverse</code> (in that order) using the <code>library()</code> function and loads the data into an object named <code>mh</code> using <code>read_csv()</code></li>
</ul>
</div>
<div id="activity-2-look-at-your-data-1" class="section level3">
<h3><span class="header-section-number">9.0.2</span> Activity 2: Look at your data</h3>
<ul>
<li>Look at your data, you can do this by clicking on the object in the environment, or using <code>summary(mh)</code> or <code>head(mh)</code>.</li>
</ul>
<p>As in Miller and Haden, we have 5 columns:</p>
<ol style="list-style-type: decimal">
<li>The participant (<code>Participant</code>),</li>
<li>Reading Ability score (<code>Abil</code>),</li>
<li>Intelligence score (<code>IQ</code>),</li>
<li>Number of minutes spent reading at home per week (<code>Home</code>),</li>
<li>And number of minutes spent watching TV per week (<code>TV</code>).</li>
</ol>
<p>For the chapter we will focus on Reading Ability and IQ but for further practice you can look at other relationships in your free time.<br />
A probable hypothesis for today could be that as Reading Ability increases so does Intelligence (think of the issue with causality and direction). Phrasing the hypothesis more formally, we hypothesise that the reading ability of school children, as measured through a standardized test, and intelligence, again measured through a standardized test, are positively correlated.</p>
</div>
<div id="activity-3-assumptions" class="section level3">
<h3><span class="header-section-number">9.0.3</span> Activity 3: Assumptions</h3>
<p>First, however, we must check some assumptions of the correlation tests. The main assumptions we need to check are:</p>
<ol style="list-style-type: decimal">
<li>Is the data interval, ratio, or ordinal?</li>
<li>Is there a data point for each participant on both variables?</li>
<li>Is the data normally distributed in both variables?</li>
<li>Does the relationship between variables appear linear?</li>
<li>Does the spread have homoscedasticity?</li>
</ol>
<p>We will look at these in turn.</p>
<div id="assumption-1-level-of-measurement" class="section level4">
<h4><span class="header-section-number">9.0.3.1</span> Assumption 1: Level of Measurement</h4>
<p>If we want to run a Pearson correlation then we need interval or ratio data; Spearman correlations can run with ordinal, interval or ratio data. What type of data do we have?</p>
<ul>
<li>The type of data in this analysis is most probably <select class='solveme' data-answer='["interval"]'> <option></option> <option>ratio</option> <option>interval</option> <option>ordinal</option> <option>nominal</option></select> as the data is <select class='solveme' data-answer='["continuous"]'> <option></option> <option>continuous</option> <option>discrete</option></select> and there is unlikely to be a true zero</li>
</ul>
<div class="solution">
<button>
Hints on data type
</button>
<ul>
<li>Are the variables continuous?</li>
<li>Is the difference between 1 and 2 on the scale equal to the difference between 2 and 3?</li>
</ul>
</div>
</div>
<div id="assumption-2-pairs-of-data" class="section level4">
<h4><span class="header-section-number">9.0.3.2</span> Assumption 2: Pairs of Data</h4>
<p>All correlations must have a data point for each participant in the two variables being correlated. This should make sense as to why - you can’t correlate against an empty cell! So now go check that you have a data point in both columns for each participant.</p>
<p>It looks like that everyone has data in all the columns but let’s test our skills a little whilst we are here. Answer the following questions:</p>
<ol style="list-style-type: decimal">
<li>How is missing data represented in a tibble? <select class='solveme' data-answer='["NA"]'> <option></option> <option>an empty cell</option> <option>NA</option> <option>a large number</option> <option>don’t know</option></select></li>
<li>Which code would leave you with just the participants who were missing Reading Ability data in mh:
<select class='solveme' data-answer='["filter(mh, is.na(Abil)"]'> <option></option> <option>filter(mh, is.na(Ability)</option> <option>filter(mh, is.na(Abil)</option> <option>filter(mh, !is.na(Ability)</option> <option>filter(mh, !is.na(Abil)</option></select></li>
<li>Which code would leave you with just the participants who were not missing Reading Ability data in mh: <select class='solveme' data-answer='["filter(mh, !is.na(Abil)"]'> <option></option> <option>filter(mh, is.na(Ability)</option> <option>filter(mh, is.na(Abil)</option> <option>filter(mh, !is.na(Ability)</option> <option>filter(mh, !is.na(Abil)</option></select></li>
</ol>
<div class="solution">
<button>
Hints on removing missing data points
</button>
<ul>
<li><code>filter(dat, is.na(variable))</code> versus <code>filter(dat, !is.na(variable))</code></li>
</ul>
</div>
</div>
<div id="assumption-3-5-normality-linearity-homoscedasticity" class="section level4">
<h4><span class="header-section-number">9.0.3.3</span> Assumption 3-5: Normality, linearity, homoscedasticity</h4>
<p>The remaining assumptions are all best checked through visualisations. You can use histograms and QQ-plots to check that the data (<code>Abil</code> and <code>IQ</code>) are both normally distributed, and you can use a scatterplot of IQ as a function of Abil to check whether the relationship is linear, with homoscedasticity, and without outliers. There are various options and tests for assessing these assumptions but today we will just use visual checks.</p>
<ul>
<li>Run the below code to create a histogram for <code>Abil</code>.</li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> mh, <span class="kw">aes</span>(<span class="dt">x =</span> Abil)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_histogram</span>()</code></pre>
<div class="figure" style="text-align: center">
<img src="09-week-6_files/figure-html/abil_hist-1.png" alt="Histogram of Abil" width="100%" />
<p class="caption">
(#fig:abil_hist)Histogram of Abil
</p>
</div>
<p>This code should look very similar to the code you used to create a bar plot in Chapter <a href="week-4.html#bar">7.0.7</a>. We have specified that we want to display <code>Abil</code> on the x-axis and that the shape we want to produce is a histogram, hence <code>geom_histogram()</code>. Just like <code>geom_bar()</code>, you do not need to specify the y-axis because if it’s a histogram, it’s always a count.</p>
<ul>
<li>Write and run the code to produce another histogram for the variable <code>IQ</code>.</li>
</ul>
<p>The QQ-plots require us to use the package <code>car</code> rather than <code>ggplot2</code>. You can make QQ-plots in <code>ggplot2</code> but they aren’t as useful, however, the code is still very simple.</p>
<ul>
<li>Run the below code to create a QQ-plot for <code>Abil</code>.</li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">qqPlot</span>(<span class="dt">x =</span> mh<span class="op">$</span>Abil)</code></pre>
<div class="figure" style="text-align: center">
<img src="09-week-6_files/figure-html/qq_abil-1.png" alt="QQ-plot for Abil" width="100%" />
<p class="caption">
(#fig:qq_abil)QQ-plot for Abil
</p>
</div>
<pre><code>## [1] 15  4</code></pre>
<p>The QQ-plot includes a <strong>confidence envelope</strong> (the blue dotted lines). The simple version is that if your data points fall within these dotted lines then you can assume normality. The <code>ggplot2</code> version of QQ-plots make it more difficult to add on this confidence envelope, which is why we’re using a different package. <code>qqPlot()</code> will also print the IDs of the data points that are potentially problematic. In this case, the 4th and 15th data point in <code>Abil</code> are flagged to review.</p>
<ul>
<li>Write and run the code to create a QQ-plot for <code>IQ</code>.</li>
</ul>
<p>In order to assess linearity and homoscedasticity, we can create a scatterplot using <code>ggplot2</code>. This code is slightly different to what you have already done with <code>ggplot()</code> in that with a scatterplot you need to specify both the x and y axis in <code>aes()</code>.</p>
<p>The first geom, <code>geom_point()</code> adds in the data points, the second geom, <code>geom_smooth</code> adds in the line of best fit. The shaded area around the line is a <strong>confidence interval</strong>.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> mh, <span class="kw">aes</span>(<span class="dt">x =</span> Abil, <span class="dt">y =</span> IQ)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>()<span class="op">+</span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> lm) <span class="co"># if you don&#39;t want the shaded CI, add se = FALSE to this</span></code></pre>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-5"></span>
<img src="09-week-6_files/figure-html/unnamed-chunk-5-1.png" alt="**CAPTION THIS FIGURE!!**" width="100%" />
<p class="caption">
Figure 9.1: <strong>CAPTION THIS FIGURE!!</strong>
</p>
</div>
<ul>
<li>Remember that <code>ggplot2</code> works on layers and that you customise each layer. Edit the above code to add in layer of <code>scale_x_continuous()</code> that changes the label <code>Abil</code> to <code>Reading Ability</code>.</li>
</ul>
<p>Based on the above visualisations:</p>
<ul>
<li>Is the assumption of normality met for both variables? <select class='solveme' data-answer='["Yes"]'> <option></option> <option>Yes</option> <option>No</option></select></li>
<li>Is the assumption of linearity met for both variables? <select class='solveme' data-answer='["Yes"]'> <option></option> <option>Yes</option> <option>No</option></select></li>
<li>Is the assumption of homoscedasticity met for both variables? <select class='solveme' data-answer='["Yes"]'> <option></option> <option>Yes</option> <option>No</option></select></li>
</ul>
<div class="solution">
<button>
Explain these answers
</button>
<p>When assessing assumptions through the use of visualisations your decision will always be a judgement call. In this dataset, we only have data from 25 participants therefore it is very unlikely we would ever observe perfect normality and linearity in this dataset. It is likely that a researcher would assume that this data is approximately normal, that there is no evidence of a non-linear relationship, and that the spread of data points around the line is relatively even.</p>
<p>Many students become fixated with needing a ‘perfect’ dataset that follows an exactly normal distribution. This is unlikely to ever happen with real data - learn to trust your instincts!</p>
</div>
<p><br></p>
<p>Look at the scatterplot and think back to the lecture, how would you describe this correlation in terms of direction and strength?</p>
</div>
</div>
<div id="activity-4-descriptive-statistics-1" class="section level3">
<h3><span class="header-section-number">9.0.4</span> Activity 4: Descriptive statistics</h3>
<p>Many researchers (and indeed members of the School of Psychology!) disagree as to whether you need to report descriptive statistics such as the mean and SD for a correlation. The argument against reporting them is that the scatterplot is actually the descriptive of the correlation that you would use to describe the potential relationship in regards to your hypothesis.</p>
<p>The counter argument is that providing descriptive statistics can still be informative about the spread of data for each variable, for example, in the current example it would make it easier to understand whether the participants as a whole compare to the population IQ score.</p>
<p>There’s no fixed answer to this question but the person writing this book takes the second view that you should always report descriptive statistics so that’s what we’re going to do.</p>
<ul>
<li>Calculate the mean score and standard deviation for <code>Abil</code> and <code>IQ</code> using <code>summarise()</code></li>
<li>Name the output of the calculations <code>Abil_mean</code>, <code>Abil_SD</code>, <code>IQ_mean</code>, and <code>IQ_SD</code>. Make sure to use these exact spellings otherwise later activities won’t work.</li>
<li>Store the output of this in an object called <code>descriptives</code> and then view the object. It should look something like this:</li>
</ul>
<table>
<thead>
<tr class="header">
<th align="center">Abil_mean</th>
<th align="center">Abil_SD</th>
<th align="center">IQ_mean</th>
<th align="center">IQ_SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">55.12</td>
<td align="center">6.08</td>
<td align="center">100.04</td>
<td align="center">9.04</td>
</tr>
</tbody>
</table>
</div>
<div id="activity-5-correlation" class="section level3">
<h3><span class="header-section-number">9.0.5</span> Activity 5: Correlation</h3>
<p>Finally we will run the correlation using the <code>cor.test()</code> function. Remember that for help on any function you can type <code>?cor.test</code> in the console window. The <code>cor.test()</code> function requires:</p>
<ul>
<li>the column name of Variable 1</li>
<li>the column name of Variable 2</li>
<li>the type of correlation you want to run: e.g. <code>pearson</code>, <code>spearman</code></li>
<li>the type of NHST tail you want to run: e.g. <code>one.sided</code>, <code>two.sided</code></li>
</ul>
<p>For example, if your data is stored in <code>dat</code> and you want to do a two-sided pearson correlation of the variables (columns) <code>X</code> and <code>Y</code>, then you would do:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor.test</span>(dat<span class="op">$</span>X, dat<span class="op">$</span>Y, <span class="dt">method =</span> <span class="st">&quot;pearson&quot;</span>, <span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</code></pre>
<ul>
<li>Based on your answers to the assumption tests, spend a couple of minutes deciding with your group which correlation method to use (e.g. pearson or spearman) and the type of NHST tail to set (e.g. two.sided or one.sided).</li>
<li>Run the correlation between IQ and Ability and save it in an object called <code>results</code>.</li>
<li>View the output by typing <code>results</code> in the console</li>
</ul>
<p>As you can see from the environment, the output from the correlation has saved as a list. This can make it a little more difficult to work with so we’re going to use a function from the <code>broom</code> package that we loaded to make the table a bit tidier. The following code is going to overwrite the object results with the tidy version.</p>
<ul>
<li>Run the below code and then view the object by clicking on <code>results</code> in the environment.</li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r">results &lt;-<span class="st"> </span>results <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># take the object results and then</span>
<span class="st">  </span><span class="kw">tidy</span>()              <span class="co"># tidy it up</span></code></pre>
</div>
<div id="activity-6-interpreting-the-correlation" class="section level3">
<h3><span class="header-section-number">9.0.6</span> Activity 6: Interpreting the correlation</h3>
<p>You should now have a tibble called <code>results</code> that gives you the output of the correlation between Reading Ability and IQ for the school children measured in Miller and Haden (2013) Chapter 11. All that is left to do now, is interpret the output.</p>
<p>Look at <code>results</code>and then with your group, answer the following questions:</p>
<ol style="list-style-type: decimal">
<li>What is the value of Pearson’s <em>r</em> to 2 decimal places? <input class='solveme nospaces' size='20' data-answer='[".45"]'/></li>
<li>The direction of the relationship between Ability and IQ is: <select class='solveme' data-answer='["positive"]'> <option></option> <option>positive</option> <option>negative</option> <option>no relationship</option></select></li>
<li>The strength of the relationship between Ability and IQ is: <select class='solveme' data-answer='["medium"]'> <option></option> <option>strong</option> <option>medium</option> <option>weak</option></select></li>
<li>Based on <span class="math inline">\(\alpha = .05\)</span> the relationship between Ability and IQ is: <select class='solveme' data-answer='["significant"]'> <option></option> <option>significant</option> <option>not significant</option></select></li>
<li>The hypothesis was that the reading ability of school children, as measured through a standardized test, and intelligence, again through a standardized test, are positively correlated. Based on the results we can say that the hypothesis: <select class='solveme' data-answer='["is supported"]'> <option></option> <option>is supported</option> <option>is not supported</option> <option>is proven</option> <option>is not proven</option></select></li>
</ol>
<div class="solution">
<button>
Explain these answers
</button>
<ol style="list-style-type: decimal">
<li>The test statistic, in this case the r value, is usually labelled as the <code>estimate</code>.</li>
<li>If Y increases as X increases then the relationship is positive. If Y increases as X decreases then the relationship is negative. If there is no change in Y as X changes then there is no relationship</li>
<li>Depending on the field most correlation values greater than .5 would be strong; .3 to .5 as medium, and .1 to .3 as small.</li>
<li>The field standard says less than .05 is significant and our p-value is less than .05.</li>
<li>Hypotheses can only be supported or not supported, never proven. In this case, our results matched our hypothesis therefore it is supported.</li>
</ol>
</div>
</div>
<div id="activity-7-write-up" class="section level3">
<h3><span class="header-section-number">9.0.7</span> Activity 7: Write-up</h3>
<p>Copy and paste the below <strong>exactly</strong> into <strong>white space</strong> in your R Markdown document and then knit the file.</p>
<pre class="sourceCode r"><code class="sourceCode r">The mean IQ score was <span class="st">`</span><span class="dt">r round(pluck(descriptives$IQ_mean),2)</span><span class="st">`</span> (<span class="st">`</span><span class="dt">r round(pluck(descriptives$IQ_SD),2)</span><span class="st">`</span>) and the mean reading ability score was <span class="st">`</span><span class="dt">r round(pluck(descriptives$Abil_mean),2)</span><span class="st">`</span> (<span class="st">`</span><span class="dt">r round(pluck(descriptives$Abil_SD),2)</span><span class="st">`</span>). A Pearson\<span class="st">`</span><span class="dt">s correlation found a significant, medium positive correlation between the two variables (r (</span><span class="st">`</span>r results<span class="op">$</span>parameter<span class="st">`</span><span class="dt">) = </span><span class="st">`</span>r <span class="kw">round</span>(results<span class="op">$</span>estimate, <span class="dv">2</span>)<span class="st">`</span><span class="dt">, *p* = </span><span class="st">`</span>r <span class="kw">round</span>(results<span class="op">$</span>p.value, <span class="dv">3</span>)<span class="st">`</span><span class="dt">).</span></code></pre>
<p>It will magically transform into:</p>
<blockquote>
<p>The mean IQ score was 100.04(9.04) and the mean reading ability score was 55.12(6.08). A Pearson`s correlation found a significant, medium positive correlation between the two variables (r (23) = 0.45, <em>p</em> = 0.024)</p>
</blockquote>
</div>
<div id="activity-8-scatterplot-matrix" class="section level3">
<h3><span class="header-section-number">9.0.8</span> Activity 8: Scatterplot matrix</h3>
<p>Above we ran one correlation and if we wanted to do a different correlation then we would have to edit the <code>cor.test()</code> line and run it again. However, when you have lots of variables in a dataset, to get a quick overview of patterns, one thing you might want to do is run all the correlations at the same time or create a matrix of scatterplots at the one time. You can do this with functions from the <code>Hmisc</code> and <code>lsr</code> packages. We will use the Miller and Haden data here again which you should still have in a tibble called <code>mh</code>.</p>
<ul>
<li>Run the following line. The <code>pairs()</code> function from the <code>Hmisc</code> library creates a matrix of scatterplots which you can then use to view all the relationships at the one time.</li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pairs</span>(mh)</code></pre>
<div class="figure" style="text-align: center"><span id="fig:pairs"></span>
<img src="09-week-6_files/figure-html/pairs-1.png" alt="Scatterplot matrix" width="100%" />
<p class="caption">
Figure 9.2: Scatterplot matrix
</p>
</div>
<p>Notice something wrong? <code>pairs()</code> will create scatterplots for <strong>all</strong> variables in your data (as will <code>correlate()</code> below). This means that it has correlated the Participant ID number as well, which is totally meaningless.</p>
<ul>
<li>Overwrite <code>mh</code> and use <code>select()</code> to get rid of the <code>Participant</code> column then run <code>pairs(mh)</code> again.</li>
</ul>
</div>
<div id="activity-9-multiple-correlations" class="section level3">
<h3><span class="header-section-number">9.0.9</span> Activity 9: Multiple correlations</h3>
<p>To perform multiple correlations in one go, we will use the <code>correlate()</code> function from the <code>lsr</code> package. If you look at the help documentation for <code>correlate()</code> you will see that it takes the following form:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">correlate</span>(x, <span class="dt">y=</span><span class="ot">NULL</span>, <span class="dt">test=</span><span class="ot">FALSE</span>, <span class="dt">corr.method=</span><span class="st">&quot;pearson&quot;</span>, <span class="dt">p.adjust.method=</span><span class="st">&quot;holm&quot;</span>) </code></pre>
<p>You can use <code>correlate()</code> similar to <code>cor.test()</code> and specify a specific variable for both <code>x</code> and <code>y</code> to perform a single correlation. However, you can also provide a data frame that has multiple variables as <code>x</code> and it will run all possible correlations between the variables.</p>
<ul>
<li><code>test</code> controls whether or not p-values will be computed. The default setting for this is <code>FALSE</code>. You will almost always want to change this to <code>TRUE</code>.<br />
</li>
<li><code>corr.method()</code> controls which correlation is computed, the default is <code>pearson</code> but if you needed to run the non-parametric version you could change this to <code>spearman</code>.<br />
</li>
<li><code>p.adjust.method</code> is the reason we are using the <code>lsr</code> package. In the lectures we discussed the problem of multiple comparisons - the idea that if you run lots and lots of tests you’re likely to produce a significant p-value just by chance. This argument applies a correction to the p-value that adjusts for the number of correlations you have performed. There are several different methods which you can look up in the help documentation, the default setting is a Bonferroni-Holm correction.<br />
</li>
<li>Because you’re running multiple correlations and some may be positive and some may be negative, there is no option to specify a one or two-tailed test.</li>
</ul>
<p>There’s one last thing we need to do before we run the correlation. <code>lsr</code> is an older package and doesn’t like working with tibbles, so we need to convert our tibble to a data frame, an older type of object.</p>
<ul>
<li>Run the below code. It will overwrite the tibble <code>mh</code> with a data frame.</li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r">mh &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(mh)</code></pre>
<p>OK, finally let’s run the correlations.</p>
<ul>
<li>Run the below code to calculate then view the correlation results</li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r">corr_results &lt;-<span class="st"> </span><span class="kw">correlate</span>(<span class="dt">x =</span> mh, <span class="co"># our data</span>
                          <span class="dt">test =</span> <span class="ot">TRUE</span>, <span class="co"># compute p-values</span>
                          <span class="dt">corr.method =</span> <span class="st">&quot;pearson&quot;</span>, <span class="co"># run a pearson test </span>
                          <span class="dt">p.adjust.method =</span> <span class="st">&quot;holm&quot;</span>) <span class="co"># use the holm correction</span>
corr_results</code></pre>
<p><code>corr_results</code> is a list with 5 components and you can view each of these separately just like you did with chi-square, for example, trying running the below code to view just the correlation values:</p>
<pre class="sourceCode r"><code class="sourceCode r">corr_results<span class="op">$</span>correlation</code></pre>
<ol style="list-style-type: decimal">
<li>Is the correlation between <code>Abil</code> and <code>Home</code> positive or negative? <select class='solveme' data-answer='["Positive"]'> <option></option> <option>Positive</option> <option>Negative</option></select></li>
<li>This means that as <code>Abil</code> scores increase, <code>Home</code> scores will <select class='solveme' data-answer='["Increase"]'> <option></option> <option>Increase</option> <option>Decrease</option></select></li>
<li>What is the strongest positive correlation? <select class='solveme' data-answer='["Abil * Home"]'> <option></option> <option>Abil * IQ</option> <option>Abil * Home</option> <option>Abil * TV</option></select></li>
<li>What is the strongest negative correlation? <select class='solveme' data-answer='["Home * TV"]'> <option></option> <option>Abil * TV</option> <option>IQ * TV</option> <option>Home * TV</option></select></li>
<li>Is the correlation between <code>Abil</code> and <code>IQ</code> significant? <select class='solveme' data-answer='["No"]'> <option></option> <option>Yes</option> <option>No</option></select></li>
<li>Is the correlation between <code>Abil</code> and <code>Home</code> significant? <select class='solveme' data-answer='["Yes"]'> <option></option> <option>Yes</option> <option>No</option></select></li>
<li>How would you describe the strength of the correlation between <code>Home</code> and <code>TV</code>? <select class='solveme' data-answer='["Strong"]'> <option></option> <option>Weak</option> <option>Medium</option> <option>Strong</option></select></li>
<li>Think back to the lecture. Why are we not calculating an effect size?</li>
</ol>
<div class="solution">
<button>
Explain these answers
</button>
<ol style="list-style-type: decimal">
<li>Negative correlations are denoted by a negative r value.
<ol start="2" style="list-style-type: decimal">
<li>Positive correlations = as one score goes up so does the other, negative correlations = as one score goes up the other goes down.<br />
3 &amp; 4. Remember that correlations take values from -1 - 1 and that the nearer to one in either direction the stronger the correlation (i.e., an r value of 0 would demonstrate a lack of any relationship.<br />
5 &amp; 6. The traditional cut-off for significance is .05. Anything below .05 is considered significant. Be careful to pay attention to decimal places.<br />
</li>
<li>Cohen’s guidelines recommend weak = 1. - .3, medium = .3 - .5, strong &gt; .5.<br />
</li>
<li>Because r is an effect size.</li>
</ol></li>
</ol>
</div>
<p><br></p>
<div id="finished-3" class="section level4">
<h4><span class="header-section-number">9.0.9.1</span> Finished!</h4>
<p>Well done! You can now add correlations to the list of things you can do in R. If you have any questions, please post them on Slack or Moodle.</p>
</div>
</div>
<div id="activity-solutions-3" class="section level3">
<h3><span class="header-section-number">9.0.10</span> Activity solutions</h3>
<div id="activity-1-1" class="section level4">
<h4><span class="header-section-number">9.0.10.1</span> Activity 1</h4>
<div class="solution">
<button>
Activity 1
</button>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(<span class="st">&quot;broom&quot;</span>)
<span class="kw">library</span>(<span class="st">&quot;car&quot;</span>)
<span class="kw">library</span>(<span class="st">&quot;lsr&quot;</span>)
<span class="kw">library</span>(<span class="st">&quot;Hmisc&quot;</span>)
<span class="kw">library</span>(<span class="st">&quot;tidyverse&quot;</span>)
mh &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;MillerHadenData.csv&quot;</span>)</code></pre>
</div>
<p><strong>click the tab to see the solution</strong>
<br></p>
</div>
<div id="activity-3-2" class="section level4">
<h4><span class="header-section-number">9.0.10.2</span> Activity 3</h4>
<div class="solution">
<button>
Activity 3
</button>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># histogram</span>
<span class="kw">ggplot</span>(<span class="dt">data =</span> mh, <span class="kw">aes</span>(<span class="dt">x =</span> IQ)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_histogram</span>()

<span class="co"># qqplot</span>
<span class="kw">qqPlot</span>(<span class="dt">x =</span> mh<span class="op">$</span>IQ)

<span class="co"># edited scatterplot</span>
<span class="kw">ggplot</span>(<span class="dt">data =</span> mh, <span class="kw">aes</span>(<span class="dt">x =</span> Abil, <span class="dt">y =</span> IQ)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>()<span class="op">+</span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> lm)<span class="op">+</span>
<span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">name =</span> <span class="st">&quot;Reading Ability&quot;</span>)</code></pre>
</div>
<p><strong>click the tab to see the solution</strong>
<br></p>
</div>
<div id="activity-5-2" class="section level4">
<h4><span class="header-section-number">9.0.10.3</span> Activity 5</h4>
<div class="solution">
<button>
Activity 5
</button>
<pre class="sourceCode r"><code class="sourceCode r">results &lt;-<span class="st"> </span><span class="kw">cor.test</span>(mh<span class="op">$</span>Abil, mh<span class="op">$</span>IQ, <span class="dt">method =</span> <span class="st">&quot;pearson&quot;</span>, <span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</code></pre>
</div>
<p><strong>click the tab to see the solution</strong>
<br></p>
</div>
<div id="activity-8-2" class="section level4">
<h4><span class="header-section-number">9.0.10.4</span> Activity 8</h4>
<div class="solution">
<button>
Activity 8
</button>
<pre class="sourceCode r"><code class="sourceCode r">mh &lt;-<span class="st"> </span>mh <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>Participant)
<span class="kw">pairs</span>(mh)</code></pre>
</div>
<p><strong>click the tab to see the solution</strong>
<br></p>

</div>
</div>
</div>



</div>
<div class="psyteachr_footer">
  
</div>
<script>

/* update total correct if #total_correct exists */
update_total_correct = function() {
  if (t = document.getElementById("total_correct")) {
    t.innerHTML =
      document.getElementsByClassName("correct").length + " of " +
      document.getElementsByClassName("solveme").length + " correct";
  }
}

/* solution button toggling function */
b_func = function() {
  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "");
  }
  
  if (my_answer !== "" & real_answers.includes(my_answer)) {
    cl.add("correct");
  } else {
    cl.remove("correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol){
    var tol = JSON.parse(this.dataset.tol);  
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("correct");
    } else {
      cl.remove("correct");
    }  
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("correct");
    }  
  }
  
  update_total_correct();
}

window.onload = function() {
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('solution')) {
      buttons[i].onclick = b_func;
    }
  }
  
  /* set up solveme inputs */
  var solveme = document.getElementsByClassName("solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off"); 
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";
    
    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;
    
    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;
  }
  
  update_total_correct();
}

</script>
            </section>

          </div>
        </div>
      </div>
<a href="week-5-r-markdown.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": {},
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
